@backendUrl=http://localhost:3000


### register with email-password approach
POST {{ backendUrl }}/auth/signup
Content-Type: application/json

{
  "username": "example",
  "email": "example@example.com",
  "password": "Ex*123456"
}
?? status == 400

### login with email-password approach
# @name login
POST {{ backendUrl }}/auth/login
Content-Type: application/json

{
  "identifier": "example@example.com",
  "password": "Ex*123456"
}

> {%
  const token = response.body.accessToken;
  client.global.set("accessToken", token);
%}
?? status == 201

### get user info
# @ref login
GET {{ backendUrl }}/users/info
Authorization: Bearer {{ accessToken }}
?? status == 200

### user change password
# @ref login
PATCH {{ backendUrl }}/users/password
Authorization: Bearer {{ accessToken }}
Content-Type: application/json

{
  "currentPassword": "Ex*123456",
  "newPassword": "Ex*123456"
}
?? status == 200

### update user info
# @ref login
PATCH {{ backendUrl }}/users/info
Authorization: Bearer {{ accessToken }}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="username"

example
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="email"

example@example.com
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="bio"

I am user example registered at growin platform
------WebKitFormBoundary7MA4YWxkTrZu0gW--
?? status == 200

### get courses
# @name courses
GET {{ backendUrl }}/courses

> {%
  const courseId = response.body[0].id;
  client.global.set("courseId", courseId);
%}
?? status == 200

### get course
# @ref courses
GET {{ backendUrl }}/courses/{{ courseId }}
?? status == 200

### search courses
GET {{ backendUrl }}/courses/search?category=Programming&minRating=3.5&sort=-createdAt&limit=4&page=1
?? status == 200

### user enrollments
# @ref login
GET {{ backendUrl }}/enrollments/my-enrollments
Authorization: Bearer {{ accessToken }}
?? status == 200

### check user enrollment
# @ref login
# @ref courses
GET {{ backendUrl }}/enrollments/is-enrolled/{{ courseId }}
Authorization: Bearer {{ accessToken }}
?? status == 200

### change user mode to instructor
# @ref login
PATCH {{ backendUrl }}/users/user-mode
Authorization: Bearer {{ accessToken }}
Content-Type: application/json

> {%
  const token = response.body.accessToken;
  client.global.set("intructorAccessToken", token);
%}

?? status == 200

### create course
# @name course
# @ref login
POST {{ backendUrl }}/courses
Authorization: Bearer {{ intructorAccessToken }}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="title"

Introduction to JavaScript
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="description"

Learn JavaScript fundamentals from scratch
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="price"

99.99
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="language"

English
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="level"

beginner
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="courseCategoryId"

1
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="course-cover.png"
Content-Type: image/png

< ./../../assets/course-cover.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

> {%
  const newCourseId = response.body.id;
  client.global.set("newCourseId", newCourseId);
%}

?? status == 201

### update course
# @ref course
# @ref login
PATCH {{ backendUrl }}/courses/{{ newCourseId }}
Authorization: Bearer {{ intructorAccessToken }}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="title"

Introduction to JavaScript
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="description"

Learn JavaScript fundamentals from scratch
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="price"

99.99
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="language"

English
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="level"

beginner
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="courseCategoryId"

1
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="course-cover.png"
Content-Type: image/png

< ./../../assets/course-cover.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

?? status == 200

### get instructor courses
# @ref login
GET {{ backendUrl }}/courses/instructor
Authorization: Bearer {{ intructorAccessToken }}
?? status == 200


### publish course
# @ref login
# @ref course
PATCH {{ backendUrl }}/courses/publish/{{ newCourseId }}
Authorization: Bearer {{ intructorAccessToken }}
?? status == 200

### create course lesson
# @name lesson
# @ref course
# @ref login
POST {{ backendUrl }}/lessons
Authorization: Bearer {{ intructorAccessToken }}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="title"

Introduction to JavaScript Lesson 1
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="position"

1
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="courseId"

{{ newCourseId }}
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="lesson-video.mp4"
Content-Type: video/mp4

< ./../../assets/lesson-video.mp4
------WebKitFormBoundary7MA4YWxkTrZu0gW--

> {%
  const newLessonId = response.body.id;
  client.global.set("newLessonId", newLessonId);
%}

?? status == 201

### get course lessons
# @ref course
# @ref login
GET {{ backendUrl }}/lessons/course/{{ newCourseId }}
?? status == 200

### get lesson
# @ref lesson
# @ref login
GET {{ backendUrl }}/lessons/{{ newLessonId }}
Authorization: Bearer {{ accessToken }}
?? status == 200


### update course lesson
# @ref lesson
# @ref login
PATCH {{ backendUrl }}/lessons/{{ newLessonId }}
Authorization: Bearer {{ intructorAccessToken }}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="title"

Introduction to JavaScript Lesson 1
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="position"

1
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="lesson-video.mp4"
Content-Type: video/mp4

< ./../../assets/lesson-video.mp4
------WebKitFormBoundary7MA4YWxkTrZu0gW--

?? status == 200

### delete lesson
# @ref lesson
# @ref login
DELETE {{ backendUrl }}/lessons/{{ newLessonId }}
Authorization: Bearer {{ intructorAccessToken }}
?? status == 200

### delete course
# @ref login
# @ref course
DELETE {{ backendUrl }}/courses/{{ newCourseId }}
Authorization: Bearer {{ intructorAccessToken }}
?? status == 200


### add to cart
# @name cart
# @ref login
POST {{ backendUrl }}/cart
Authorization: Bearer {{ accessToken }}
Content-Type: application/json

{
  "courseId": 3
}

?? status == 201

### get cart
# @ref login
# @ref cart
GET {{ backendUrl }}/cart
Authorization: Bearer {{ accessToken }}
?? status == 200

### remove course from cart
# @ref login
# @ref cart
POST {{ backendUrl }}/cart/remove-course
Authorization: Bearer {{ accessToken }}
Content-Type: application/json

{
  "courseId": 3
}

?? status == 201

### delete cart
# @ref login
# @ref cart
DELETE {{ backendUrl }}/cart
Authorization: Bearer {{ accessToken }}
?? status == 200

### get course categories
GET {{ backendUrl }}/course-categories
?? status == 200


### write review
# @ref login
# @ref course
POST {{ backendUrl }}/reviews/{{ newCourseId }}
Authorization: Bearer {{ accessToken }}
Content-Type: application/json

{
  "rating": 4,
  "comment": "this course is awesome",
  "helpful": true
}

?? status == 201

### update review
# @ref login
# @ref course
PATCH {{ backendUrl }}/reviews/{{ newCourseId }}
Authorization: Bearer {{ accessToken }}
Content-Type: application/json

{
  "rating": 3,
  "comment": "this course was very bad",
  "helpful": false
}

?? status == 200

### delete review
# @ref login
# @ref course
DELETE {{ backendUrl }}/reviews/{{ newCourseId }}
Authorization: Bearer {{ accessToken }}
Content-Type: application/json

?? status == 200

### change user mode to leaner
# @ref login
PATCH {{ backendUrl }}/users/user-mode
Authorization: Bearer {{ accessToken }}
Content-Type: application/json

> {%
  const token = response.body.accessToken;
  client.global.set("accessToken", token);
%}
?? status == 200